name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: .go-version
          cache: true

      - name: vet
        run: go vet $(go list ./... | grep -v vendor)

      - name: lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.11.3

      - name: test
        run: ./scripts/test.sh

      - name: coverage
        uses: k1LoW/octocov-action@v1
